// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uecljvnuuwkvdxcmveho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlY2xqdm51dXdrdmR4Y212ZWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2MjE4NDIsImV4cCI6MjA1MzE5Nzg0Mn0.S8RTt2YH_rb6Z2TS0ua9kMbvlz3KWMeAcdAe54O6SHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);